### ISSUE TITLE
Transaction tracking and management

### ISSUE THREAD

**Issue by elaineo** [ethereumproject/emerald-wallet#107]
Right now, transactions are tracked after submitting through the wallet. A few issues are unclear (not sure if all of them are necessary):

- [ ] there is no option to "un-track" the transaction 
- [ ] there a way to "watch" a transaction (maybe this is a job for block explorer, not wallet)
- [x] tracked transactions are in local storage and disappear when the wallet is refreshed. #116
