### ISSUE TITLE
Beta Release

### ISSUE THREAD

**Issue by splix** [ethereumproject/emerald-wallet#121]
What to finish before release:

 * [x] launch Geth from Electron - #122 
 * [x] download Geth if not exists
 * [x] launch Connector from Electron - #165 
 * [x] hide support for Address Book, Tokens and Contracts for now - #146
 * [x] switch between local node and remote (gastracker/epool) - #139
 * [x] few issues on sent transaction form
 * [x] new UX for address screen - #142
 * [x] new UX for transaction details screen - #128
 * [x] new UI for header
 * [x] current transactions history (sent/received after app launch) - #123, #124, #176 
 * [x] show value in USD - #126
 * [x] "Add ETC" popup - #127
 * [x] first launch screen - #140
 * [x] bundle as distributable app - #141
 * [x] texts - #158, #159

**Comment by whilei** [comment]
The _new UI for header_ is the one from `design.png`, yes?

**Comment by splix** [comment]
right, not sure if i've published it here

**Comment by caochao** [comment]
why hide support for contract/token?
