### ISSUE TITLE
Beta release

### ISSUE THREAD

**Issue by splix** [ethereumproject/emerald-wallet#252]
### Bugs

- [x] Requires extra lib on Windows - #220, ethereumproject/emerald-rs#173

###  Design

- [x] General color/style schema
- [x] Header - #260
- [x] Create TX form - #261
- [x] TX details screen - #262

### New Features

- [x] Import addr from Ledger - #253
- [x] Backup PK
- [ ] ~~Import raw PK~~

### Release

- [x] tag v0.4.0

### Notes

 - Just basic stuff for design at the moment

**Comment by splix** [comment]
Done https://github.com/ethereumproject/emerald-wallet/releases/tag/v0.4.0
